services:
  bot:
    container_name: discord-soundboard-bot
    image: ghcr.io/pascaldevenoge/discord-soundboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5123:5123
    environment:
      - DISCORD_SBRD_TOKEN=${DISCORD_SBRD_TOKEN}
      - NUMBA_CACHE_DIR=/tmp
    volumes:
      - type: bind
        source: ${DISCORD_SBRD_DATA_DIR}
        target: /app/data

    stop_signal: SIGINT
    init: true
    restart: always
