services:
  bot:
    container_name: discord-soundboard-bot
    image: ghcr.io/PascalDevenoge/discord-soundboard-bot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5123:5123
    environment:
      - DISCORD_SBRD_TOKEN=${DISCORD_SBRD_TOKEN}
      - NUMBA_CACHE_DIR=/tmp
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - type: bind
        source: ./tracks
        target: /app/tracks
    stop_signal: SIGINT
    init: true