name: Docker image build job

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: ${{ gitea.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build front-end
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - run: npm ci
      - run: npm run build

      - name: Install Docker
        uses: papodaca/install-docker-action@main

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: http://raspberry-pi-4:3000/
          username: ${{ gitea.actor }}
          password: ${{ secrets.CONTAINER_REG_ACCESS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."raspberry-pi-4:3000"]
              http = true
              insecure = true            

      - name: Build image and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          tags: raspberry-pi-4:3000/pascaldevenoge/discord-soundboard:${{ gitea.ref_name }}, raspberry-pi-4:3000/pascaldevenoge/discord-soundboard:latest
          push: true
          provenance: false
