name: Docker image build 2

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Docker login
        run: docker login --username pascaldevenoge --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Build
        run: docker build . --tag ghcr.io/pascaldevenoge/discord-soundboard:latest -f Dockerfile
      - name: Publish
        run: docker push ghcr.io/pascaldevenoge/discord-soundboard:latest